export const DISHES = [
  {
    id: "pasta-alfredo",
    name: "Truffle Alfredo Pasta",
    price: "₦4,200",
    desc: "Handmade fettuccine, rich cream, black truffle oil, Parmigiano-Reggiano.",
    img: "/images/demo/delizia-kitchen/truffle-alfredo.webp",
    category: "Mains",
  },
  {
    id: "chicken-deluxe",
    name: "Chicken Deluxe",
    price: "₦3,400",
    desc: "Herb-crusted chicken breast, garlic butter, roasted seasonal veg.",
    img: "/images/demo/delizia-kitchen/chicken-deluxe.webp",
    category: "Mains",
  },
  {
    id: "cheesecake",
    name: "Classic Cheesecake",
    price: "₦1,200",
    desc: "Velvety New York style cheesecake with berry compote.",
    img: "/images/demo/delizia-kitchen/cheesecake.webp",
    category: "Desserts",
  },
  {
    id: "garden-salad",
    name: "Delizia Garden Salad",
    price: "₦1,000",
    desc: "Crisp greens, toasted seeds, citrus vinaigrette.",
    img: "/images/demo/delizia-kitchen/garden-salad.webp",
    category: "Starters",
  },
  {
    id: "garlic-bread",
    name: "Smoky Garlic Bread",
    price: "₦700",
    desc: "Wood-fired ciabatta, garlic-herb butter, pecorino.",
    img: "/images/demo/delizia-kitchen/garlic-bread.webp",
    category: "Starters",
  },
  {
    id: "ice-cream",
    name: "Salted Caramel Gelato",
    price: "₦800",
    desc: "House churned gelato with caramel shards.",
    img: "/images/demo/delizia-kitchen/caramel-gelato.webp",
    category: "Desserts",
  },
];